# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.27+.
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: server
    image: local/pontoon
    depends_on:
      - postgresql
    ports:
      - '8088:8000'
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgresql/${DATABASE_DB}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_DEV=${DJANGO_DEV}
      - ENABLE_INSIGHTS=${ENABLE_INSIGHTS}
      - FXA_CLIENT_ID=${FXA_CLIENT_ID}
      - FXA_OAUTH_ENDPOINT=${FXA_OAUTH_ENDPOINT}
      - FXA_PROFILE_ENDPOINT=${FXA_PROFILE_ENDPOINT}
      - FXA_SECRET_KEY=${FXA_SECRET_KEY}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=${PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION}
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
      - SITE_URL=${SITE_URL}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}

  # Database
  postgresql:
    image: postgres:17
    environment:
      # Create the superuser account
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
